### DISCUSSION TITLE
https://ewan.my/

### DISCUSSION THREAD

**Discussion by giscus** [Gassandrid/ewan.my#48] [Announcements]
# https://ewan.my/

image/svg+xml Openclipart Hello! My name is Ewan You may or may not know me from San Francisco or Vermont.

https://ewan.my/

**Comment by macvellian** [comment]
Woah cool song

**Reply by Gassandrid** [reply]
thanks! it is Veridis Quo by Daft Punk

**Reply by macvellian** [reply]
Ok

**Comment by msgoldsm** [comment]
This is actually so fire 🥹

**Comment by kenkyo0** [comment]
Hi, do you have a video or a guide, how to set up obsidian like you did?
=

**Reply by Gassandrid** [reply]
I do not, but now that you mention it I think that is something I will do. I will likely put it under the [[Website]] page if you check in later.

**Reply by kenkyo0** [reply]
Thank you very much, you would put in this effort to do this. :D

**Reply by wala343** [reply]
This would be super interesting, I watched your interview and it reminded my why I don't use my own obsidian much. I'm looking forward to what you do.

**Reply by Gassandrid** [reply]
Done, see https://ewan.my/tags/journal/workflow 

These get quite abstract, and it is important to note that I have abandoned a lot of the old workfllow ideas. The main ones are to develop pure frontmatter templates, in combination with web clipper, and just throw the content into your vault. I have a very nitpicky system for consuming information, see "Consuming and Choosing Content Effectively".

By far the most thought out workflow to start with is the CEOs, see https://stephango.com/vault

**Reply by LeosPetzold** [reply]
I'm so glad I found this :D
Thank you!!

**Comment by hugoocoto** [comment]
What software do you use for the website? I write more than one site generator but they're not as simple as what I'm looking for. I love your obsidian setup btw

**Reply by Gassandrid** [reply]
This is Quartz! Thank you for the kind words. Quartz is awesome, specifically made for obsidian markdown and highly customizable. Have a look at https://quartz.jzhao.xyz/

**Comment by ning-wx** [comment]
Could you share your Obsidian Primary theme custom colour CSS file?

**Reply by Gassandrid** [reply]
Of course!  Here it is:

```css
.theme-light {
    --background-primary: #f5f1eb;
    --background-primary-alt: #f5f1eb;
    --background-secondary: #e6dfd6;
    --background-secondary-alt: #e6dfd6;
    --background-modifier-hover: rgba(166, 124, 109, 0.15); 

    --text-normal: #2d2520;
    --text-muted: #4a4238;
    --text-faint: #9a8f82;
    --text-on-accent: #f5f1eb; 

    --interactive-accent: #a67c6d;
    --interactive-accent-hover: #8b7f73;
    --text-accent: #a67c6d;
    --text-accent-hover: #8b7f73;
    
    --background-modifier-border: #f5f1eb; 
    --background-modifier-border-hover: #e6dfd6;
    --interactive-normal: #f5f1eb;
    --interactive-hover: #e6dfd6;

    --hr-color: #4a4238;
    --caret-color: #bf6159; 
    
    --graph-line: #8b7f73;
    --graph-node: #a67c6d;

    /* --- Semantic Colors --- */
    --color-red: #bf6159;
    --color-orange: #c78d75;
    --color-yellow: #cc9e54;
    --color-green: #869c7a;
    --color-cyan: #56706b;
    --color-blue: #728c99;
    --color-purple: #9d868e;
    --color-pink: #9d868e;
}

.theme-dark {
    --background-primary: #1a1714;
    --background-primary-alt: #1a1714;
    --background-secondary: #2a2520;
    --background-secondary-alt: #2a2520;
    --background-modifier-hover: rgba(197, 155, 141, 0.15);

    --text-normal: #ebe7e1;
    --text-muted: #d4cec7;
    --text-faint: #6b6158;
    --text-on-accent: #1a1714;

    --interactive-accent: #c59b8d;
    --interactive-accent-hover: #a89a8d;
    --text-accent: #c59b8d;
    --text-accent-hover: #a89a8d;

    --background-modifier-border: #1a1714;
    --background-modifier-border-hover: #2a2520;
    --interactive-normal: #1a1714;
    --interactive-hover: #2a2520;

    --hr-color: #d4cec7;
    --caret-color: #db8e88; 

    --graph-line: #4a4238;
    --graph-node: #c59b8d;

    --color-red: #db8e88;
    --color-orange: #deaea0;
    --color-yellow: #e0bc7e;
    --color-green: #aebd9f;
    --color-cyan: #8daeb3;
    --color-blue: #9bb0bd;
    --color-purple: #c9b1b9;
    --color-pink: #c9b1b9;
}

.cm-cursorLayer .cm-cursor {
    background-color: var(--caret-color) !important;
    opacity: 0.6; 
}
```

**Comment by wlygon7** [comment]
This is cool! You have definitely inspired me to rethink how I use Obsidian, take notes, and how to build my own website. I've been very unhappy with the design I have WIP rn, but I think with Quartz I can get exactly what I want. Thank you, you're awesome!

**Reply by Gassandrid** [reply]
Thanks for the kind words! No worries about your website, you should have seen how bad this looked just 3 months ago. It is a constant time sync but its finally become something I can be proud of.

**Comment by reiKloske** [comment]
This is very interesting, I also do believe that the deep combination of Biology/Neuroscience and Computer Science will lead the field of AI in the years to come. Keep up the hard work, brother!

**Reply by Gassandrid** [reply]
My thoughts exactly. With all the advancements in learning to model human cognition and our effective output, it is only a matter of time before we turn these models inward on ourselves. A most exciting time to be alive.

**Comment by ArcerionDev** [comment]
hello! do you have a full list of the plugins you use for obsidian you can share? i noticed a lot of plugins that seemed very effective for the workflow you have in place and i'm super curious what they're called so i can also give them a try :)

**Reply by Gassandrid** [reply]
will be making a video going into detail very soon!

**Comment by lelax7** [comment]
Hi, thank you for the insights in the interview :) The style in which you use Obsidian is very inspiring and unique. How exactly do you manage your images and files that are not .md? Because iirc, you can't add metadata/properties to those directly. Thank you!

**Reply by Gassandrid** [reply]
I have been developing a plugin to convert obsidian into a media management tool, although I am designing it with the intention to run in a completely different vault. It works by creating markdown files for each media piece, and extracting metadata like GPS and main colors to the YAML frontmatter. Might publish soon! Although wont be put on the official plugin repo as that requires a lot of cleaning

**Comment by NolanChai** [comment]
This is really neat, and found you from the interview. Seems we may share some interests - I'm a recent graduate from UCSD, and majored in Cognitive Science (specializing in Neural Computation), Mathematics-Computer Science, and Linguistics. I'm currently taking some time to work on research & probably do a post-bac / spend a bit of time in industry before eventually going back for a PhD, but would love to connect and discuss papers or work whenever.

**Reply by Gassandrid** [reply]
That is so awesome. I would enjoy that, I love meeting people with like-minded interests. I am 100% going to go for a PhD as well although I am a bit further away from that than you! Please feel free to add me on discord @gassandrid

**Comment by Lyroxide** [comment]
Also came from the interview :) We NEED the entire Obsidian setup!!

**Reply by Gassandrid** [reply]
I honestly might just make a video of my own since everyone keeps asking me to explain it! Would be nice as I can prepare a little better instead of blabbering on without direction.

**Reply by LeosPetzold** [reply]
I'm planning to start using obsidian in my free studies as well, especially after stepping down from grammar school to basic high school to focus more on myself.
I hope I can mirror your setup on some kind of Linux distro perhaps, even if just visually.
You should of course take this as an encouragement to make such video.

**Reply by Gassandrid** [reply]
video has been filmed! being edited I imagine. in the mean time have a look at https://ewan.my/Thoughts/Colophon-For-Mind-Structure

**Comment by moen0** [comment]
Greetings!I found your interview really insightful, you also finally convinced me to embrace Obsidian. I'm doing 1st year of my Bachelor's in IT and found your ideas of Mind Mapping really interesting. Will definitely keep posted for more of your stuff!

**Reply by Gassandrid** [reply]
thanks for the kind words!

**Comment by BasedVault** [comment]
Hey, saw a few replies up that you were making a video on your Obsidian setup. Is it out yet?

**Reply by Gassandrid** [reply]
I have been planning to, but mid terms are killing me! 100% coming out soon, might make it another collab with sylvan.

**Reply by kushvinth** [reply]
eagerly waiting

**Reply by Gassandrid** [reply]
video up soon! has been recorded. in the mean time have a look at https://ewan.my/Thoughts/Colophon-For-Mind-Structure

**Comment by kushvinth** [comment]
How did you hide the, macos traffic button.

**Reply by Gassandrid** [reply]
simple little plugin I created for myself, css snippet didnt seem to work for me so I just made a plugin with the following:

**main.js**:
```js
const { Plugin } = require("obsidian");

/** @type {(w: Electron.BrowserWindow) => void} */
function hideWindowControls(w) {
  w.setWindowButtonVisibility(false);
}

module.exports = class extends Plugin {
  onload() {
    if (process.platform === "darwin") {
      hideWindowControls(electronWindow);

      this.app.workspace.on("window-open", (_, { activeWindow }) => {
        hideWindowControls(activeWindow);
      });
    }
  }
};
```

**styles.css**:
```css
body.mod-macos .workspace-tab-header-container {
  padding-left: 4px !important;
}
```
